import { MuiTelInputCountry } from 'mui-tel-input';

// dummy translate fn for extraction
const t = (str: string) => str;

export type CountryCode = MuiTelInputCountry;

export const countries: { [code: string]: string } = {
  AT: t('Austria'),
  CH: t('Switzerland'),
  DE: t('Germany'),
  EE: t('Estonia'),
  NL: t('Netherlands'),
  SK: t('Slovakia'),
  BG: t('Bulgaria'),
  AU: t('Australia'),
  CZ: t('Czechia'),
  PL: t('Poland'),
  CL: t('Chile'),
  BE: t('Belgium'),
  HK: t('Hong Kong'),
  NZ: t('New Zealand'),
  HU: t('Hungary'),
  GB: t('United Kingdom'),
  ES: t('Spain'),
  NO: t('Norway'),
  BR: t('Brazil'),
  SG: t('Singapore'),
  ZA: t('South Africa'),
  CO: t('Colombia'),
  IE: t('Ireland'),
  LI: t('Liechtenstein'),
  LT: t('Lithuania'),
  GR: t('Greece'),
  DK: t('Denmark'),
  TH: t('Thailand'),
  CN: t('China'),
  MX: t('Mexico'),
  US: t('United States of America'),
  MT: t('Malta'),
  RO: t('Romania'),
  IT: t('Italy'),
  CY: t('Cyprus'),
  SI: t('Slovenia'),
  PT: t('Portugal'),
  FI: t('Finland'),
  TR: t('Turkey'),
  HR: t('Croatia'),
  FR: t('France'),
  LV: t('Latvia'),
  CA: t('Canada'),
  MC: t('Monaco'),
  LU: t('Luxembourg'),
  MY: t('Malaysia'),
  SE: t('Sweden'),
};
